### ISSUE TITLE
Validation during creating the chat

### ISSUE THREAD

**Issue by dmitryt** [dogecodes/react-chat-api#9]
I suppose, field `title` should be required for `Chat` model.
At least it's required on frontend side in existed example.
But user can create a chat without it:

**Request**:
`curl -XPOST -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YjAzOTc2ODIwOWUxMjMzNjJiNzAyOTUiLCJpYXQiOjE1MjczMjY3MDIsImV4cCI6MTUyODE5MDcwMn0.RXe3RIc9IUbVRChHtE5x3ikoDZhrfMa8CwSCeydkNoU" -H "Content-Type: application/json; charset=utf-8" -d '{"data": {}}' http://localhost:8000/v1/chats`

**Response**:
`{"success":true,"message":"Chat has been created","chat":{"_id":"5b09c6c08dee7a274be0a54e","updatedAt":"2018-05-26T20:42:40.981Z","createdAt":"2018-05-26T20:42:40.981Z","creator":{"_id":"5b039768209e123362b70295","username":"asd","lastName":"","firstName":""},"members":[],"__v":0}}`

Moreover, if I don't provide data, backend will return 500:
**Request**:
`curl -XPOST -i -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YjAzOTc2ODIwOWUxMjMzNjJiNzAyOTUiLCJpYXQiOjE1MjczMjY3MDIsImV4cCI6MTUyODE5MDcwMn0.RXe3RIc9IUbVRChHtE5x3ikoDZhrfMa8CwSCeydkNoU" -H "Content-Type: application/json; charset=utf-8" http://localhost:8000/v1/chats`

**Response**:
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 2210
Date: Sat, 26 May 2018 20:51:53 GMT
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;title&#39; of undefined<br> &nbsp; &nbsp;at Object.newChat (/Users/gremlin/education/doge/react-chat-api/controllers/chats.js:174:17)<br> &nbsp; &nbsp;at chatsRouter.post (/Users/gremlin/education/doge/react-chat-api/routes/chats.js:27:6)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at Function.handle (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:174:3)<br> &nbsp; &nbsp;at router (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:47:12)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/Users/gremlin/education/doge/react-chat-api/node_modules/express/lib/router/index.js:275:10)</pre>
</body>
</html>
```

**Comment by denysdovhan** [comment]
Please open a PR with a fix 🙏
